# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [2]:
!pip install -U tensorflow==2.0

  Stored in directory: C:\Users\SKUMARJH\AppData\Local\pip\Cache\wheels\5c\2e\7e\a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
  Stored in directory: C:\Users\SKUMARJH\AppData\Local\pip\Cache\wheels\8e\28\49\fad4e7f0b9a1227708cbbee4487ac8558a7334849cb81c813d
  Stored in directory: C:\Users\SKUMARJH\AppData\Local\pip\Cache\wheels\7c\06\54\bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6
  Stored in directory: C:\Users\SKUMARJH\AppData\Local\pip\Cache\wheels\2c\b1\94\43d03e130b929aae7ba3f8d15cbd7bc0d1cb5bb38a5c721833
Successfully built gast absl-py termcolor opt-einsum


In [10]:
%tensorflow_version 2.X

UsageError: Line magic function `%tensorflow_version` not found.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [3]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [4]:
from sklearn import datasets
import pandas as pd
import numpy as np

In [77]:
iris = datasets.load_iris()

In [78]:
x=iris.data

In [79]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [80]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [81]:
y=iris.target

In [82]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [83]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [84]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25,random_state=30)  

In [29]:
!pip install keras

In [85]:
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense,Dropout,Activation,Flatten
#from keras.layers.convolutional import Conv2D,MaxPooling2D
from keras.utils import np_utils
from sklearn import metrics
import matplotlib.pyplot as plt
%matplotlib inline

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [86]:
#Encoding the output class label (One-Hot Encoding)
y_train=np_utils.to_categorical(y_train,3)
y_test=np_utils.to_categorical(y_test,3)

In [87]:
y_train

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1

In [88]:
y_test

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [0]:
keras library 

## Question 5

### Initialize a sequential model
- Define a sequential model

In [16]:
from tensorflow.keras import layers
model=tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [89]:
from tensorflow.keras.layers import Dense


In [90]:
model.add(Dense(4, activation='sigmoid', input_shape=(4,)))

In [91]:
model.add(Dense(3, activation='softmax'))

In [92]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 20        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 16        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [93]:
model.compile(loss='categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [94]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 20        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 16        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 15        
Total params: 66
Trainable params: 66
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [101]:
model.fit(X_train,y_train,nb_epoch=100,verbose=1,validation_data=(X_test,y_test))

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 0s 321us/sample - loss: 1.0856 - accuracy: 0.6875 - val_loss: 1.0967 - val_accuracy: 0.6053
Epoch 2/100
112/112 [==============================] - 0s 285us/sample - loss: 1.0854 - accuracy: 0.6875 - val_loss: 1.0968 - val_accuracy: 0.6053
Epoch 3/100
112/112 [==============================] - 0s 205us/sample - loss: 1.0853 - accuracy: 0.6875 - val_loss: 1.0967 - val_accuracy: 0.6053
Epoch 4/100
112/112 [==============================] - 0s 205us/sample - loss: 1.0854 - accuracy: 0.6875 - val_loss: 1.0966 - val_accuracy: 0.6053
Epoch 5/100
112/112 [==============================] - 0s 187us/sample - loss: 1.0852 - accuracy: 0.6875 - val_loss: 1.0965 - val_accuracy: 0.6053
Epoch 6/100
112/112 [==============================] - 0s 321us/sample - loss: 1.0852 - accuracy: 0.6875 - val_loss: 1.0965 - val_accuracy: 0.6053
Epoch 7/100
112/112 [==============================] - 0s 205us/sample - 

112/112 [==============================] - 0s 232us/sample - loss: 1.0835 - accuracy: 0.6875 - val_loss: 1.0954 - val_accuracy: 0.6053
Epoch 56/100
112/112 [==============================] - 0s 267us/sample - loss: 1.0836 - accuracy: 0.6875 - val_loss: 1.0955 - val_accuracy: 0.6053
Epoch 57/100
112/112 [==============================] - 0s 258us/sample - loss: 1.0833 - accuracy: 0.6875 - val_loss: 1.0956 - val_accuracy: 0.6053
Epoch 58/100
112/112 [==============================] - 0s 588us/sample - loss: 1.0833 - accuracy: 0.6875 - val_loss: 1.0953 - val_accuracy: 0.6053
Epoch 59/100
112/112 [==============================] - ETA: 0s - loss: 1.0870 - accuracy: 0.65 - 0s 338us/sample - loss: 1.0832 - accuracy: 0.6875 - val_loss: 1.0952 - val_accuracy: 0.6053
Epoch 60/100
112/112 [==============================] - 0s 196us/sample - loss: 1.0832 - accuracy: 0.6875 - val_loss: 1.0953 - val_accuracy: 0.6053
Epoch 61/100
112/112 [==============================] - 0s 356us/sample - loss: 1.0

## Question 10

### Make predictions
- Predict labels on one row

In [99]:
model.predict(X_test[0:1])

array([[0.35310364, 0.33868074, 0.30821568]], dtype=float32)

In [100]:
y_test[0:1]

array([[1., 0., 0.]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

TypeError: 'numpy.ndarray' object is not callable

In [40]:
score = model.evaluate(X_test, y_test,verbose=1)
print(score)

38/1 [==================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [277]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [278]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [0]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

In [46]:
df1 = pd.read_csv("prices.csv")

In [47]:
df1.head()

date symbol        open       close         low        high  \
0  2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998  126.250000   
1  2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002  125.540001   
2  2016-01-07 00:00:00   WLTW  116.379997  114.949997  114.930000  119.739998   
3  2016-01-08 00:00:00   WLTW  115.480003  116.620003  113.500000  117.440002   
4  2016-01-11 00:00:00   WLTW  117.010002  114.970001  114.089996  117.330002   

      volume  
0  2163600.0  
1  2386400.0  
2  2489500.0  
3  2006300.0  
4  1408600.0

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [48]:
df1=df1.drop(labels=['date','symbol'],axis=1)

In [49]:
df1.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

In [50]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 5 columns):
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5)
memory usage: 32.5 MB


In [51]:
df1=df1.iloc[0:1000,:]

In [285]:
df1.shape

(1000, 5)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
# covered in above step

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [52]:
X = df1.drop('volume', axis=1)

In [53]:
y = df1['volume']

In [54]:
y = np.divide(y, 1000000)

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [55]:
X=X.to_numpy()

In [56]:
print(X.shape)

(1000, 4)


In [57]:
y=y.to_numpy()

In [58]:
print(y.shape)

(1000,)


In [59]:
X = X.astype('float32')

In [60]:
print(X.dtype)

float32


In [61]:
y = y.astype('float32')

In [62]:
print(y.dtype)

float32


## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [63]:
tf.math.l2_normalize(
    X,
    axis=None,
    epsilon=1e-12,
    name=None
)

<tf.Tensor: id=3557, shape=(1000, 4), dtype=float32, numpy=
array([[0.02202894, 0.02245906, 0.02182905, 0.02253223],
       [0.02235197, 0.02141321, 0.02140607, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051192, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.0079956 , 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [298]:
W = tf.Variable(tf.zeros(shape=[4,1]), name="Weights")
b = tf.Variable(tf.zeros(shape=[1]),name="Bias")

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [299]:
loss = tf.reduce_mean(tf.square(y_preds-y),name='Loss')


In [300]:
loss

<tf.Tensor: id=47168, shape=(), dtype=float32, numpy=237.28665>

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

### Observe values of Weight
- Print the updated values

In [301]:
w.numpy()

array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

### Observe values of Bias
- Print the updated values

In [64]:
W = tf.zeros(shape=(4, 1000))
b = tf.zeros(shape=(1000))

In [65]:
def prediction(X, W, b):
    
    y_pred = tf.add(tf.matmul(X, W), b)
    return y_pred

In [66]:
def loss(y_actual, y_predicted):
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    return avg
    

In [67]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
# Record mathematical operations on 'tape' to calculate loss
     with tf.GradientTape() as t:
        
        t.watch([w,b])
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
        dw, db = t.gradient(current_loss,[w, b])
    # Update Weights and Bias
        w = w - learning_rate * dw
        b = b - learning_rate * db
        return w, b
for i in range(100):
    
    W, b = train(X, y, W, b)
    print('Current Training Loss on iteration', i, loss(y, prediction(X, W, b)).numpy())
    

Current Training Loss on iteration 0 121.451195
Current Training Loss on iteration 1 105.40982
Current Training Loss on iteration 2 103.18689
Current Training Loss on iteration 3 102.877396
Current Training Loss on iteration 4 102.83285
Current Training Loss on iteration 5 102.825
Current Training Loss on iteration 6 102.82224
Current Training Loss on iteration 7 102.82016
Current Training Loss on iteration 8 102.8182
Current Training Loss on iteration 9 102.81624
Current Training Loss on iteration 10 102.814285
Current Training Loss on iteration 11 102.81234
Current Training Loss on iteration 12 102.81039
Current Training Loss on iteration 13 102.808426
Current Training Loss on iteration 14 102.80648
Current Training Loss on iteration 15 102.80451
Current Training Loss on iteration 16 102.80256
Current Training Loss on iteration 17 102.800606
Current Training Loss on iteration 18 102.79866
Current Training Loss on iteration 19 102.79671
Current Training Loss on iteration 20 102.794754

In [69]:
W.numpy()

array([[0.00441789, 0.00487283, 0.00508335, ..., 0.07586285, 0.01341253,
        0.01144351],
       [0.00475111, 0.00524036, 0.00546676, ..., 0.08158487, 0.01442418,
        0.01230664],
       [0.0041793 , 0.00460967, 0.00480882, ..., 0.0717659 , 0.01268818,
        0.01082549],
       [0.00501202, 0.00552814, 0.00576698, ..., 0.08606518, 0.01521628,
        0.01298247]], dtype=float32)

In [70]:
b.numpy()

array([1.91349909e-03, 2.11054459e-03, 2.20172619e-03, 1.77438138e-03,
       1.24577386e-03, 9.71076603e-04, 8.39831016e-04, 6.94523100e-04,
       9.67273954e-04, 1.34739140e-03, 1.46271777e-03, 8.35143961e-04,
       6.58793200e-04, 6.22444612e-04, 4.98008565e-04, 7.92515464e-04,
       6.01748936e-04, 6.63215178e-04, 5.07825462e-04, 6.14484539e-04,
       7.92692008e-04, 8.45756556e-04, 8.81840242e-04, 1.06172787e-03,
       1.52577541e-03, 1.72105199e-03, 1.16697210e-03, 8.15775245e-04,
       1.04810868e-03, 8.14978965e-04, 3.89934081e-04, 1.10046519e-03,
       6.02545275e-04, 3.63667379e-04, 3.95594281e-04, 4.94559295e-04,
       4.06737789e-04, 8.59288033e-04, 6.13865326e-04, 1.02555624e-03,
       7.82433024e-04, 6.12008269e-04, 7.94196036e-04, 7.46880018e-04,
       7.04428763e-04, 3.68619949e-04, 5.21975919e-04, 4.37868963e-04,
       4.56176174e-04, 4.97124158e-04, 7.15749047e-04, 1.42150430e-03,
       8.85554531e-04, 6.29165617e-04, 3.92852759e-04, 4.72360756e-04,
      